# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info

hello_world:

sensor:
  platform: example_sensor

light:
  - platform: example_light
    host: localhost
    username: sss
    password: 123456

# Text to speech
# tts:
#   - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
